In [1]:
import numpy as np

##Datatype &Attribute

In [2]:
#numpy's main datatypes in ndarray
a1=np.array([1,2,3,4])

In [3]:
a1

array([1, 2, 3, 4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3]
            ,[3,4,5]])

In [7]:
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
a3=np.array([[1,2,3]
            ,[3,4,5]
            ,[6,7,8]])
a3

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
a3=np.array([[[1,2,3]
            ,[3,4,5]
            ,[6,7,8]],
             [[9,10,11],
              [12,13,14],
              [15,16,17]]
            ])
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [10]:
a1.shape

(4,)

In [11]:
 a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [14]:
a1.dtype

dtype('int32')

In [15]:
a1.size

4

In [16]:
a2.size

6

In [17]:
a3.size

18

In [18]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
## create a data frame from numpy
import pandas as pd

In [20]:
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  3  4  5

In [21]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zeros=np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array=np.arange(0,10,2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array=np.random.randint(0,10,size=(3,3))

In [27]:
random_array

array([[0, 1, 5],
       [8, 4, 5],
       [8, 6, 3]])

In [28]:
random_array.size

9

In [29]:
random_array.shape

(3, 3)

In [30]:
random_array2=np.random.random((5,3))

In [31]:
random_array2

array([[0.66911119, 0.55710713, 0.15199278],
       [0.23483451, 0.93104448, 0.88576317],
       [0.76073737, 0.45952062, 0.46530388],
       [0.33249032, 0.3007458 , 0.70456853],
       [0.75192385, 0.79392488, 0.73804802]])

In [32]:
random_array2.shape

(5, 3)

In [33]:
random_array2.size

15

In [34]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.64851874, 0.6828268 , 0.77009497],
       [0.12847786, 0.18443091, 0.05254008],
       [0.30263797, 0.17357438, 0.66120362],
       [0.88767254, 0.95374032, 0.44817248],
       [0.87565555, 0.79663792, 0.33010261]])

In [44]:
##Pseudo-random numbers
np.random.seed(seed=0)
random_array4=np.random.randint(10,size=(5,3))

In [45]:
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

#  3.viewing  array and matrices

In [52]:
np.unique(random_array4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [53]:
a1

array([1, 2, 3, 4])

In [54]:
a2


array([[1, 2, 3],
       [3, 4, 5]])

In [55]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [56]:
a1[0]

1

In [59]:
a2[1]

array([3, 4, 5])

In [60]:
a2.shape

(2, 3)

In [49]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [50]:
a3[:2,:3,:1]

array([[[ 1],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]]])

In [51]:
a6=np.random.randint(10,size=(2,3,4,5))

a6

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [81]:
a6[:3,:3,:4,:1]

array([[[[2],
         [1],
         [9],
         [0]],

        [[9],
         [5],
         [8],
         [9]],

        [[2],
         [6],
         [4],
         [8]]],


       [[[9],
         [7],
         [0],
         [6]],

        [[4],
         [9],
         [1],
         [0]],

        [[3],
         [6],
         [6],
         [6]]]])

# Manipulating and comparing array

Arithmetic


In [91]:
a1

array([1, 2, 3, 4])

In [86]:
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [88]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
a2 + one

array([[2., 3., 4.],
       [4., 5., 6.]])

In [93]:
a2*one

array([[1., 2., 3.],
       [3., 4., 5.]])

In [95]:
a2-one

array([[0., 1., 2.],
       [2., 3., 4.]])

In [98]:
a2.shape

(2, 3)

In [99]:
a2.reshape(2,3,1).shape

(2, 3, 1)